# GitHub API Configuration
github:
  # Create a personal access token at https://github.com/settings/tokens
  # Needs repo and read:org permissions
  token: "your_github_personal_access_token"

# Organizations to back up
organizations:
  - org_name1
  - org_name2
  # Add more organizations as needed

# Backup Configuration
backup:
  # Path where repositories will be backed up
  path: "/volume1/backups/github"
  # How many days to keep backup logs
  log_retention_days: 30